// Curated brain-size dataset across the animal kingdom.
//
// brainMass in grams, bodyMass in kilograms.
// neurons in BILLIONS (approximate / representative figures from comparative
// neuroanatomy literature, e.g. Herculano-Houzel et al.).
// eq = encephalization quotient (brain size vs. expected for body mass;
// drawn from Jerison's EQ tables and later work). These are rounded for
// visualization and easy to refine.
//
// color is inherited from the category palette (see categoryColors) so the
// legend stays consistent as species are added.

export const HUMAN_BRAIN_MASS = 1350; // reference for true-scale

export const categoryColors = {
  primate: 0xff6b6b,
  cetacean: 0x4d96ff,
  mammal: 0xb0a8a0,
  bird: 0xffd166,
  cephalopod: 0x9b5de5,
  reptile: 0x6bbf59,
  fish: 0x37b6a5,
  insect: 0xe0c341,
  arachnid: 0xc98b2b,
};

const C = categoryColors;

export const species = [
  // ---- Primates ----
  {
    id: "human",
    name: "Human",
    scientific: "Homo sapiens",
    category: "primate",
    brainMass: 1350,
    bodyMass: 62,
    neurons: 86,
    eq: 7.5,
    color: C.primate,
    fact: "The human brain packs ~86 billion neurons and is ~7-8x larger than expected for a mammal our size (EQ).",
  },
  {
    id: "chimpanzee",
    name: "Chimpanzee",
    scientific: "Pan troglodytes",
    category: "primate",
    brainMass: 420,
    bodyMass: 52,
    neurons: 28,
    eq: 2.4,
    color: C.primate,
    fact: "Our closest living relative; a chimp brain has ~28 billion neurons — roughly a third of the human count.",
  },
  {
    id: "gorilla",
    name: "Gorilla",
    scientific: "Gorilla gorilla",
    category: "primate",
    brainMass: 500,
    bodyMass: 207,
    neurons: 33,
    eq: 1.7,
    color: C.primate,
    fact: "A gorilla's brain is about a third the size of a human's, yet its cortex is just as thick — it simply has fewer neurons.",
  },
  {
    id: "orangutan",
    name: "Orangutan",
    scientific: "Pongo pygmaeus",
    category: "primate",
    brainMass: 370,
    bodyMass: 50,
    neurons: 20,
    eq: 1.8,
    color: C.primate,
    fact: "Highly intelligent tool-users; their brains are smaller than gorillas' but similarly neuron-dense.",
  },
  {
    id: "baboon",
    name: "Baboon",
    scientific: "Papio anubis",
    category: "primate",
    brainMass: 137,
    bodyMass: 10.6,
    neurons: 10,
    eq: 2.0,
    color: C.primate,
    fact: "Complex social hierarchies and strong spatial memory for food caching.",
  },
  {
    id: "macaque",
    name: "Rhesus Macaque",
    scientific: "Macaca mulatta",
    category: "primate",
    brainMass: 97,
    bodyMass: 6.8,
    neurons: 9,
    eq: 2.0,
    color: C.primate,
    fact: "A workhorse of neuroscience — its ~9 billion neurons map closely onto the human blueprint.",
  },
  {
    id: "gibbon",
    name: "Gibbon",
    scientific: "Hylobates lar",
    category: "primate",
    brainMass: 120,
    bodyMass: 6,
    neurons: 8,
    eq: 1.8,
    color: C.primate,
    fact: "Agile brachiators with brains comparable in neuron count to much heavier monkeys.",
  },
  {
    id: "capuchin",
    name: "Capuchin",
    scientific: "Cebus capucinus",
    category: "primate",
    brainMass: 58,
    bodyMass: 4,
    neurons: 6,
    eq: 4.8,
    color: C.primate,
    fact: "Has one of the highest EQs among monkeys — famous for using stones to crack nuts.",
  },
  {
    id: "lemur",
    name: "Ring-tailed Lemur",
    scientific: "Lemur catta",
    category: "primate",
    brainMass: 24,
    bodyMass: 2.2,
    neurons: 3,
    eq: 1.2,
    color: C.primate,
    fact: "A prosimian — its smaller, older-style brain still supports rich social lives.",
  },
  {
    id: "marmoset",
    name: "Common Marmoset",
    scientific: "Callithrix jacchus",
    category: "primate",
    brainMass: 7.7,
    bodyMass: 0.35,
    neurons: 2,
    eq: 1.5,
    color: C.primate,
    fact: "Tiny New World monkey with a surprisingly high neuron density for its size.",
  },

  // ---- Cetaceans ----
  {
    id: "sperm-whale",
    name: "Sperm Whale",
    scientific: "Physeter macrocephalus",
    category: "cetacean",
    brainMass: 7800,
    bodyMass: 35000,
    neurons: 50,
    eq: 1.8,
    color: C.cetacean,
    fact: "Holds the record for the largest brain ever — about 5-6x the mass of a human brain.",
  },
  {
    id: "blue-whale",
    name: "Blue Whale",
    scientific: "Balaenoptera musculus",
    category: "cetacean",
    brainMass: 6800,
    bodyMass: 120000,
    neurons: 50,
    eq: 1.0,
    color: C.cetacean,
    fact: "The largest animal ever, yet its relative brain size is modest for a whale.",
  },
  {
    id: "elephant",
    name: "African Elephant",
    scientific: "Loxodonta africana",
    category: "mammal",
    brainMass: 5700,
    bodyMass: 6654,
    neurons: 257,
    eq: 1.3,
    color: C.mammal,
    fact: "An elephant brain can weigh over 5.7 kg and has ~257 billion neurons — more than humans, mostly outside the cortex.",
  },
  {
    id: "orca",
    name: "Orca (Killer Whale)",
    scientific: "Orcinus orca",
    category: "cetacean",
    brainMass: 5600,
    bodyMass: 6000,
    neurons: 50,
    eq: 1.8,
    color: C.cetacean,
    fact: "Big-brained social predators with region-specific dialects passed down through family pods.",
  },
  {
    id: "humpback-whale",
    name: "Humpback Whale",
    scientific: "Megaptera novaeangliae",
    category: "cetacean",
    brainMass: 4675,
    bodyMass: 30000,
    neurons: 40,
    eq: 1.0,
    color: C.cetacean,
    fact: "Its song is one of the most complex vocal behaviours in the animal kingdom.",
  },
  {
    id: "dolphin",
    name: "Bottlenose Dolphin",
    scientific: "Tursiops truncatus",
    category: "cetacean",
    brainMass: 1550,
    bodyMass: 300,
    neurons: 58,
    eq: 5.3,
    color: C.cetacean,
    fact: "The highest brain-to-body ratio of any cetacean and an EQ second only to humans among mammals.",
  },
  {
    id: "beluga",
    name: "Beluga",
    scientific: "Delphinapterus leucas",
    category: "cetacean",
    brainMass: 2400,
    bodyMass: 1100,
    neurons: 20,
    eq: 1.5,
    color: C.cetacean,
    fact: "Its highly folded cortex and social calls earned it the nickname 'sea canary'.",
  },

  // ---- Birds ----
  {
    id: "crow",
    name: "Crow",
    scientific: "Corvus corone",
    category: "bird",
    brainMass: 7,
    bodyMass: 0.5,
    neurons: 2,
    eq: 2.5,
    color: C.bird,
    fact: "Birds have the largest brain-to-body ratios among avians. Crows solve puzzles, use tools and recognise faces.",
  },
  {
    id: "raven",
    name: "Raven",
    scientific: "Corvus corax",
    category: "bird",
    brainMass: 10,
    bodyMass: 1.2,
    neurons: 2,
    eq: 2.5,
    color: C.bird,
    fact: "Planning, deception and problem-solving on par with great apes relative to brain size.",
  },
  {
    id: "macaw",
    name: "Macaw",
    scientific: "Ara macao",
    category: "bird",
    brainMass: 8,
    bodyMass: 1,
    neurons: 1,
    eq: 2.5,
    color: C.bird,
    fact: "Parrots and corvids top the avian IQ charts despite walnut-sized brains.",
  },
  {
    id: "owl",
    name: "Owl",
    scientific: "Strix aluco",
    category: "bird",
    brainMass: 2.2,
    bodyMass: 1.5,
    neurons: 0.2,
    eq: 1.5,
    color: C.bird,
    fact: "Asymmetric ears and a swivelling head turn a small brain into a precise hunter.",
  },
  {
    id: "pigeon",
    name: "Pigeon",
    scientific: "Columba livia",
    category: "bird",
    brainMass: 2,
    bodyMass: 0.4,
    neurons: 0.2,
    eq: 2.0,
    color: C.bird,
    fact: "Can recognise hundreds of images and was the first animal to pass a concept of 'same/different'.",
  },
  {
    id: "eagle",
    name: "Bald Eagle",
    scientific: "Haliaeetus leucocephalus",
    category: "bird",
    brainMass: 10,
    bodyMass: 5,
    neurons: 1,
    eq: 1.5,
    color: C.bird,
    fact: "Tiny visual centres give it eyesight up to 8x sharper than a human's.",
  },
  {
    id: "ostrich",
    name: "Ostrich",
    scientific: "Struthio camelus",
    category: "bird",
    brainMass: 40,
    bodyMass: 100,
    neurons: 1,
    eq: 0.3,
    color: C.bird,
    fact: "The biggest bird, but its brain is smaller than its eyeball.",
  },
  {
    id: "chicken",
    name: "Chicken",
    scientific: "Gallus gallus",
    category: "bird",
    brainMass: 4,
    bodyMass: 2,
    neurons: 0.3,
    eq: 0.5,
    color: C.bird,
    fact: "Can count, show self-control and dream in REM — more cognitively complex than assumed.",
  },

  // ---- Other mammals ----
  {
    id: "horse",
    name: "Horse",
    scientific: "Equus caballus",
    category: "mammal",
    brainMass: 655,
    bodyMass: 521,
    neurons: 2,
    eq: 0.6,
    color: C.mammal,
    fact: "Despite a large brain, horses have relatively few cortical neurons — body size drives the mass.",
  },
  {
    id: "cow",
    name: "Cow",
    scientific: "Bos taurus",
    category: "mammal",
    brainMass: 425,
    bodyMass: 700,
    neurons: 3,
    eq: 0.5,
    color: C.mammal,
    fact: "Recognises individual herd members and forms preferential friendships.",
  },
  {
    id: "giraffe",
    name: "Giraffe",
    scientific: "Giraffa camelopardalis",
    category: "mammal",
    brainMass: 680,
    bodyMass: 529,
    neurons: 2,
    eq: 0.5,
    color: C.mammal,
    fact: "Its brain sits 2 m above the heart — a tight blood-pressure system prevents fainting when it bends down.",
  },
  {
    id: "camel",
    name: "Camel",
    scientific: "Camelus dromedarius",
    category: "mammal",
    brainMass: 762,
    bodyMass: 650,
    neurons: 2,
    eq: 0.6,
    color: C.mammal,
    fact: "A relatively large brain for an ungulate, supporting navigation across featureless deserts.",
  },
  {
    id: "polar-bear",
    name: "Polar Bear",
    scientific: "Ursus maritimus",
    category: "mammal",
    brainMass: 498,
    bodyMass: 450,
    neurons: 1.5,
    eq: 0.6,
    color: C.mammal,
    fact: "Spends most of its brainpower on tracking scent trails of seals across ice.",
  },
  {
    id: "lion",
    name: "Lion",
    scientific: "Panthera leo",
    category: "mammal",
    brainMass: 240,
    bodyMass: 190,
    neurons: 1.5,
    eq: 0.5,
    color: C.mammal,
    fact: "Social cats whose cooperation is coordinated by a modest but well-connected brain.",
  },
  {
    id: "tiger",
    name: "Tiger",
    scientific: "Panthera tigris",
    category: "mammal",
    brainMass: 263,
    bodyMass: 220,
    neurons: 1.5,
    eq: 0.5,
    color: C.mammal,
    fact: "Solitary ambush hunters with large territories mapped mentally across scent marks.",
  },
  {
    id: "hippopotamus",
    name: "Hippopotamus",
    scientific: "Hippopotamus amphibius",
    category: "mammal",
    brainMass: 582,
    bodyMass: 1500,
    neurons: 1.5,
    eq: 0.3,
    color: C.mammal,
    fact: "A heavy brain for its bulk, yet among the lowest EQ values of any mammal.",
  },
  {
    id: "rhinoceros",
    name: "Rhinoceros",
    scientific: "Rhinoceros unicornis",
    category: "mammal",
    brainMass: 500,
    bodyMass: 2000,
    neurons: 1.5,
    eq: 0.3,
    color: C.mammal,
    fact: "Massive body, modest brain — most of its behaviour is instinctive and olfactory.",
  },
  {
    id: "dog",
    name: "Dog (Beagle)",
    scientific: "Canis lupus familiaris",
    category: "mammal",
    brainMass: 72,
    bodyMass: 10,
    neurons: 2,
    eq: 1.2,
    color: C.mammal,
    fact: "Fewer cortical neurons than cats (160M vs 300M) despite a heavier brain — cat neurons are denser.",
  },
  {
    id: "wolf",
    name: "Gray Wolf",
    scientific: "Canis lupus",
    category: "mammal",
    brainMass: 119,
    bodyMass: 36,
    neurons: 0.5,
    eq: 1.0,
    color: C.mammal,
    fact: "A brain built for endurance pursuit and tight pack coordination.",
  },
  {
    id: "red-fox",
    name: "Red Fox",
    scientific: "Vulpes vulpes",
    category: "mammal",
    brainMass: 50,
    bodyMass: 4.2,
    neurons: 0.3,
    eq: 1.0,
    color: C.mammal,
    fact: "Uses the Earth's magnetic field to triangulate pounces on prey under snow.",
  },
  {
    id: "grey-seal",
    name: "Gray Seal",
    scientific: "Halichoerus grypus",
    category: "mammal",
    brainMass: 325,
    bodyMass: 85,
    neurons: 1,
    eq: 1.0,
    color: C.mammal,
    fact: "Can recognise individual human faces and remember them for years.",
  },
  {
    id: "sheep",
    name: "Sheep",
    scientific: "Ovis aries",
    category: "mammal",
    brainMass: 140,
    bodyMass: 55.5,
    neurons: 1.5,
    eq: 0.7,
    color: C.mammal,
    fact: "Can recognise the faces of at least 50 other sheep and of familiar humans.",
  },
  {
    id: "pig",
    name: "Pig",
    scientific: "Sus scrofa",
    category: "mammal",
    brainMass: 180,
    bodyMass: 192,
    neurons: 1.5,
    eq: 0.4,
    color: C.mammal,
    fact: "Surprisingly clever — can learn mirroring tasks and play simple video games.",
  },
  {
    id: "goat",
    name: "Goat",
    scientific: "Capra hircus",
    category: "mammal",
    brainMass: 115,
    bodyMass: 27.7,
    neurons: 1,
    eq: 0.6,
    color: C.mammal,
    fact: "Excels at tricky spatial puzzles and remembers solutions for months.",
  },
  {
    id: "kangaroo",
    name: "Red Kangaroo",
    scientific: "Macropus rufus",
    category: "mammal",
    brainMass: 56,
    bodyMass: 35,
    neurons: 0.5,
    eq: 0.6,
    color: C.mammal,
    fact: "A marsupial brain — smaller relative to body than in placental mammals.",
  },
  {
    id: "platypus",
    name: "Platypus",
    scientific: "Ornithorhynchus anatinus",
    category: "mammal",
    brainMass: 9,
    bodyMass: 1.5,
    neurons: 0.2,
    eq: 0.5,
    color: C.mammal,
    fact: "A monotreme whose brain processes electric fields from prey through its bill.",
  },
  {
    id: "opossum",
    name: "Opossum",
    scientific: "Didelphis virginiana",
    category: "mammal",
    brainMass: 6,
    bodyMass: 1.7,
    neurons: 0.2,
    eq: 0.5,
    color: C.mammal,
    fact: "Tiny-brained but remarkably resistant to snake venom and rabies.",
  },
  {
    id: "guinea-pig",
    name: "Guinea Pig",
    scientific: "Cavia porcellus",
    category: "mammal",
    brainMass: 5.5,
    bodyMass: 1.04,
    neurons: 0.2,
    eq: 0.6,
    color: C.mammal,
    fact: "A classic lab mammal with a lissencephalic (smooth) brain and few folds.",
  },
  {
    id: "rabbit",
    name: "Rabbit",
    scientific: "Oryctolagus cuniculus",
    category: "mammal",
    brainMass: 12,
    bodyMass: 2.5,
    neurons: 0.5,
    eq: 0.5,
    color: C.mammal,
    fact: "A respectable relative brain size for a prey animal built to flee.",
  },
  {
    id: "squirrel",
    name: "Gray Squirrel",
    scientific: "Sciurus carolinensis",
    category: "mammal",
    brainMass: 7.6,
    bodyMass: 0.5,
    neurons: 0.2,
    eq: 1.0,
    color: C.mammal,
    fact: "Spatial memory lets it relocate thousands of buried nuts each season.",
  },
  {
    id: "rat",
    name: "Rat",
    scientific: "Rattus norvegicus",
    category: "mammal",
    brainMass: 2,
    bodyMass: 0.28,
    neurons: 0.2,
    eq: 0.4,
    color: C.mammal,
    fact: "A primary model organism — its brain maps almost identically onto the mammalian plan.",
  },
  {
    id: "hedgehog",
    name: "Hedgehog",
    scientific: "Erinaceus europaeus",
    category: "mammal",
    brainMass: 3.4,
    bodyMass: 0.785,
    neurons: 0.1,
    eq: 0.5,
    color: C.mammal,
    fact: "Hibernates for months — its brain tolerates body temperatures near freezing.",
  },
  {
    id: "little-brown-bat",
    name: "Little Brown Bat",
    scientific: "Myotis lucifugus",
    category: "mammal",
    brainMass: 0.25,
    bodyMass: 0.01,
    neurons: 0.05,
    eq: 0.5,
    color: C.mammal,
    fact: "Echolocation is computed in real time by a brain weighing a fraction of a gram.",
  },
  {
    id: "cat",
    name: "Cat",
    scientific: "Felis catus",
    category: "mammal",
    brainMass: 30,
    bodyMass: 4.5,
    neurons: 1,
    eq: 1.0,
    color: C.mammal,
    fact: "Smaller brain than a dog, but denser — giving cats nearly twice as many cortical neurons as dogs.",
  },
  {
    id: "mouse",
    name: "Mouse",
    scientific: "Mus musculus",
    category: "mammal",
    brainMass: 0.4,
    bodyMass: 0.023,
    neurons: 0.07,
    eq: 0.5,
    color: C.mammal,
    fact: "Tiny but mighty: a mouse brain is ~1.7% of its body mass, a ratio similar to humans.",
  },

  // ---- Reptiles ----
  {
    id: "alligator",
    name: "Alligator",
    scientific: "Alligator mississippiensis",
    category: "reptile",
    brainMass: 8.4,
    bodyMass: 200,
    neurons: 0.05,
    eq: 0.2,
    color: C.reptile,
    fact: "A small, ancient-style brain — but alligators can use tools to lure prey.",
  },
  {
    id: "komodo-dragon",
    name: "Komodo Dragon",
    scientific: "Varanus komodoensis",
    category: "reptile",
    brainMass: 8,
    bodyMass: 70,
    neurons: 0.05,
    eq: 0.2,
    color: C.reptile,
    fact: "The largest lizard; its brain is small but supports learned hunting tactics.",
  },
  {
    id: "turtle",
    name: "Red-eared Slider",
    scientific: "Trachemys scripta",
    category: "reptile",
    brainMass: 0.5,
    bodyMass: 1,
    neurons: 0.01,
    eq: 0.1,
    color: C.reptile,
    fact: "A minuscule brain, yet it can be trained to navigate simple mazes.",
  },
  {
    id: "python",
    name: "Python",
    scientific: "Python regius",
    category: "reptile",
    brainMass: 1,
    bodyMass: 50,
    neurons: 0.02,
    eq: 0.1,
    color: C.reptile,
    fact: "Heat-sensing pits feed a brain that tracks warm-blooded prey in the dark.",
  },

  // ---- Fish ----
  {
    id: "goldfish",
    name: "Goldfish",
    scientific: "Carassius auratus",
    category: "fish",
    brainMass: 0.097,
    bodyMass: 0.2,
    neurons: 0.0001,
    eq: 0.05,
    color: C.fish,
    fact: "Often underestimated — it can distinguish shapes and remember them for months.",
  },
  {
    id: "great-white-shark",
    name: "Great White Shark",
    scientific: "Carcharodon carcharias",
    category: "fish",
    brainMass: 32,
    bodyMass: 1000,
    neurons: 0.005,
    eq: 0.1,
    color: C.fish,
    fact: "A large brain for a fish, with regions specialised for smell and electroreception.",
  },
  {
    id: "manta-ray",
    name: "Manta Ray",
    scientific: "Mobula birostris",
    category: "fish",
    brainMass: 30,
    bodyMass: 1000,
    neurons: 0.005,
    eq: 0.1,
    color: C.fish,
    fact: "Has the biggest brain-to-body ratio of any fish and shows curiosity toward divers.",
  },

  // ---- Cephalopods ----
  {
    id: "octopus",
    name: "Octopus",
    scientific: "Octopus vulgaris",
    category: "cephalopod",
    brainMass: 40,
    bodyMass: 20,
    neurons: 0.5,
    eq: 1.0,
    color: C.cephalopod,
    fact: "About 500 million neurons — two-thirds of them in the arms, which can taste and act autonomously.",
  },
  {
    id: "squid",
    name: "Squid",
    scientific: "Loligo pealeii",
    category: "cephalopod",
    brainMass: 5,
    bodyMass: 5,
    neurons: 0.3,
    eq: 0.5,
    color: C.cephalopod,
    fact: "A ring of nerve cords around the esophagus acts as a distributed 'brain'.",
  },

  // ---- Insects & arachnids ----
  {
    id: "honey-bee",
    name: "Honey Bee",
    scientific: "Apis mellifera",
    category: "insect",
    brainMass: 0.001,
    bodyMass: 0.0001,
    neurons: 0.00095,
    eq: 1.0,
    color: C.insect,
    fact: "Just ~950,000 neurons run a brain that maps the sun, counts landmarks and dances directions.",
  },
  {
    id: "ant",
    name: "Ant",
    scientific: "Formica rufa",
    category: "insect",
    brainMass: 0.0003,
    bodyMass: 0.000005,
    neurons: 0.00025,
    eq: 1.0,
    color: C.insect,
    fact: "Up to ~15% of its body mass is brain — one of the highest ratios in the animal kingdom.",
  },
  {
    id: "fruit-fly",
    name: "Fruit Fly",
    scientific: "Drosophila melanogaster",
    category: "insect",
    brainMass: 0.0001,
    bodyMass: 0.000002,
    neurons: 0.0001,
    eq: 0.5,
    color: C.insect,
    fact: "A 100,000-neuron brain that learns, sleeps and forms memories — a genetics superstar.",
  },
  {
    id: "jumping-spider",
    name: "Jumping Spider",
    scientific: "Phidippus audax",
    category: "arachnid",
    brainMass: 0.0005,
    bodyMass: 0.00002,
    neurons: 0.0003,
    eq: 1.0,
    color: C.arachnid,
    fact: "Tiny but it can plan detours and recognise faces — the smartest of the arthropods.",
  },
];
