// Curated brain-size dataset (sources: faculty.washington.edu/chudler/facts.html,
// SOCR / Open University brain-body weight tables, Wikipedia brain-body mass ratio).
// brainMass in grams, bodyMass in kilograms. Values marked approx are estimates
// where no precise figure was available.

// note: neuron counts (billions) and EQ are approximate/representative figures
// drawn from comparative neuroanatomy literature (Herculano-Houzel et al.,
// Jerison's EQ tables) and rounded for visualization clarity.

export const HUMAN_BRAIN_MASS = 1350; // reference for true-scale

export const species = [
  {
    id: "human",
    name: "Human",
    scientific: "Homo sapiens",
    category: "primate",
    brainMass: 1350,
    bodyMass: 62,
    neurons: 86,
    eq: 7.5,
    color: 0xff6b6b,
    fact: "The human brain packs ~86 billion neurons. Despite not being the largest, it is ~7-8x bigger than expected for a mammal our size (encephalization quotient).",
  },
  {
    id: "sperm-whale",
    name: "Sperm Whale",
    scientific: "Physeter macrocephalus",
    category: "cetacean",
    brainMass: 7800,
    bodyMass: 35000,
    neurons: 50,
    eq: 1.8,
    color: 0x4d96ff,
    fact: "Holds the record for the largest brain of any animal ever — about 5-6x the mass of a human brain.",
  },
  {
    id: "elephant",
    name: "African Elephant",
    scientific: "Loxodonta africana",
    category: "mammal",
    brainMass: 5700,
    bodyMass: 6654,
    neurons: 257,
    eq: 1.3,
    color: 0x9b7653,
    fact: "An elephant brain can weigh over 5.7 kg. It has roughly 257 billion neurons — more than humans — but most live outside the cortex.",
  },
  {
    id: "dolphin",
    name: "Bottlenose Dolphin",
    scientific: "Tursiops truncatus",
    category: "cetacean",
    brainMass: 1550,
    bodyMass: 300,
    neurons: 58,
    eq: 5.3,
    color: 0x6bcB77,
    fact: "Dolphins have the highest brain-to-body ratio of any cetacean and an encephalization quotient second only to humans among mammals.",
  },
  {
    id: "gorilla",
    name: "Gorilla",
    scientific: "Gorilla gorilla",
    category: "primate",
    brainMass: 500,
    bodyMass: 207,
    neurons: 33,
    eq: 1.7,
    color: 0x8d99ae,
    fact: "A gorilla's brain is about a third the size of a human's, yet its cerebral cortex is just as thick — it simply has fewer neurons.",
  },
  {
    id: "chimpanzee",
    name: "Chimpanzee",
    scientific: "Pan troglodytes",
    category: "primate",
    brainMass: 420,
    bodyMass: 52,
    neurons: 28,
    eq: 2.4,
    color: 0xc98bb9,
    fact: "Our closest living relative. A chimp brain has ~28 billion neurons — roughly a third of the human count.",
  },
  {
    id: "dog",
    name: "Dog (Beagle)",
    scientific: "Canis lupus familiaris",
    category: "mammal",
    brainMass: 72,
    bodyMass: 10,
    neurons: 2,
    eq: 1.2,
    color: 0xe9c46a,
    fact: "Dogs have fewer cortical neurons than cats (160M vs 300M) despite a heavier brain — cat neurons are packed more densely.",
  },
  {
    id: "octopus",
    name: "Octopus",
    scientific: "Octopus vulgaris",
    category: "cephalopod",
    brainMass: 40,
    bodyMass: 20,
    neurons: 0.5,
    eq: 1.0,
    color: 0x9b5de5,
    fact: "About 500 million neurons — two-thirds of them in the arms, which can taste and act with surprising autonomy.",
  },
  {
    id: "cat",
    name: "Cat",
    scientific: "Felis catus",
    category: "mammal",
    brainMass: 30,
    bodyMass: 4.5,
    neurons: 1,
    eq: 1.0,
    color: 0xf4a261,
    fact: "Smaller brain than a dog, but denser — giving cats nearly twice as many cortical neurons as dogs.",
  },
  {
    id: "crow",
    name: "Crow",
    scientific: "Corvus corone",
    category: "bird",
    brainMass: 7,
    bodyMass: 0.5,
    neurons: 2,
    eq: 2.5,
    color: 0xffd166,
    fact: "Birds have the largest brain-to-body ratios among avians. Crows solve puzzles, use tools and recognise human faces.",
  },
  {
    id: "rabbit",
    name: "Rabbit",
    scientific: "Oryctolagus cuniculus",
    category: "mammal",
    brainMass: 12,
    bodyMass: 2.5,
    neurons: 0.5,
    eq: 0.5,
    color: 0xd9c2a3,
    fact: "A rabbit's brain is about 10% of its body mass ratio story: small absolute size, but a respectable relative one.",
  },
  {
    id: "mouse",
    name: "Mouse",
    scientific: "Mus musculus",
    category: "mammal",
    brainMass: 0.4,
    bodyMass: 0.023,
    neurons: 0.07,
    eq: 0.5,
    color: 0xb0b0b0,
    fact: "Tiny but mighty: a mouse brain is ~1.7% of its body mass, a ratio similar to humans — small animals punch above their weight.",
  },
];

export const categoryColors = {
  mammal: 0xb0a8a0,
  primate: 0xff6b6b,
  cetacean: 0x4d96ff,
  bird: 0xffd166,
  cephalopod: 0x9b5de5,
};
